export const cartTypes = {
	TOGGLE_SET_HIDDEN: 'TOGGLE_SET_HIDDEN',
	ADD_ITEMS: 'ADD_ITEMS',
	REMOVE_ITEM_CART: 'REMOVE_ITEM_CART',
	CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
	CLEAR_CART: 'CLEAR_CART'
};
